package cn.orangepoet.inaction.algorithm;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Foo {
    // There is an array generated by a rule.
    // The first item is 1. If k is in the array, then 3k+1 and 2k+1 are in the array.
    // The array is sorted. There are no duplicate values.
    // Please write a function that accepts an input N. It should return the value at index N of the array.
    // For example [1, 3, 4, 7, 9, 10, 13, 15, 19, 21, 22, 27, ...] n=10, return 22; n=100, return 447

    public static int findN(int n) {
        ArrayDeque<Integer> queue = new ArrayDeque<>();
        queue.push(1);

        List<Integer> lst = new ArrayList<>();
        Set<Integer> unique = new HashSet<>();

        int t = 0;
        while (!queue.isEmpty()) {
            int size = queue.size();
            for (int i = 0; i < size; i++) {
                int item = queue.poll();
                if (unique.add(item)) {
                    lst.add(item);
                }
                int item1 = item * 3 + 1;
                int item2 = item * 2 + 1;
                queue.offer(item1);
                queue.offer(item2);
            }
            if (lst.size() >= n) {
                break;
            }
        }
        Collections.sort(lst);
        return lst.get(n);
    }

    public static void main(String[] args) {
        int ans = findN(10);
        System.out.println(ans);
        //
    }
}
